-- CATEGORIAS
INSERT INTO CATEGORIA (NOME, DESCRICAO) VALUES ('Eletrônicos', 'Produtos eletrônicos');
INSERT INTO CATEGORIA (NOME, DESCRICAO) VALUES ('Livros', 'Livros de diversos gêneros');
INSERT INTO CATEGORIA (NOME, DESCRICAO) VALUES ('Roupas', 'Vestuário masculino e feminino');

-- PRODUTOS
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, PRECO_ATUAL, QUANTIDADE, ESTOQUE, CATEGORIA_ID) VALUES
('Smartphone', 'Celular Android', 2000.00, 2000.00, 10, 10, 1);
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, PRECO_ATUAL, QUANTIDADE, ESTOQUE, CATEGORIA_ID) VALUES
('Notebook', 'Notebook i5', 3500.00, 3500.00, 5, 5, 1);
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, PRECO_ATUAL, QUANTIDADE, ESTOQUE, CATEGORIA_ID) VALUES
('Fone Bluetooth', 'Fone sem fio', 200.00, 200.00, 30, 30, 1);
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, PRECO_ATUAL, QUANTIDADE, ESTOQUE, CATEGORIA_ID) VALUES
('Livro Java', 'Aprenda Java', 80.00, 80.00, 15, 15, 2);
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, PRECO_ATUAL, QUANTIDADE, ESTOQUE, CATEGORIA_ID) VALUES
('Livro Spring', 'Spring Boot para Iniciantes', 90.00, 90.00, 10, 10, 2);
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, PRECO_ATUAL, QUANTIDADE, ESTOQUE, CATEGORIA_ID) VALUES
('Livro Front-end', 'HTML, CSS e JS', 70.00, 70.00, 20, 20, 2);
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, PRECO_ATUAL, QUANTIDADE, ESTOQUE, CATEGORIA_ID) VALUES
('Camiseta', 'Camiseta Algodão', 50.00, 50.00, 40, 40, 3);
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, PRECO_ATUAL, QUANTIDADE, ESTOQUE, CATEGORIA_ID) VALUES
('Calça Jeans', 'Calça Masculina', 120.00, 120.00, 25, 25, 3);
INSERT INTO PRODUTO (NOME, DESCRICAO, PRECO, PRECO_ATUAL, QUANTIDADE, ESTOQUE, CATEGORIA_ID) VALUES
('Vestido', 'Vestido Feminino', 150.00, 150.00, 12, 12, 3);

-- PEDIDOS
-- INSERT INTO PEDIDOS (DATA_PEDIDO, STATUS, VALOR_TOTAL, CLIENTE_ID) VALUES
--('2025-05-30T10:00:00', 'CONFIRMADO', 2150.00, 1);

--INSERT INTO PEDIDOS (DATA_PEDIDO, STATUS, VALOR_TOTAL, CLIENTE_ID) VALUES
--('2025-05-30T11:15:00', 'ENVIADO', 90.00, 1);

--INSERT INTO PEDIDOS (DATA_PEDIDO, STATUS, VALOR_TOTAL, CLIENTE_ID) VALUES
--('2025-05-30T14:30:00', 'CANCELADO', 120.00, 2);



-- PEDIDO_PRODUTO
--INSERT INTO PEDIDO_PRODUTO (PRECO_UNITARIO, QUANTIDADE, SUBTOTAL, PEDIDO_ID, PRODUTO_ID, DESCONTO) VALUES
--(2000.00, 1, 2000.00, 1, 1, 0.00);

--INSERT INTO PEDIDO_PRODUTO (PRECO_UNITARIO, QUANTIDADE, SUBTOTAL, PEDIDO_ID, PRODUTO_ID, DESCONTO) VALUES
--(200.00, 1, 200.00, 1, 3, 0.00);

--INSERT INTO PEDIDO_PRODUTO (PRECO_UNITARIO, QUANTIDADE, SUBTOTAL, PEDIDO_ID, PRODUTO_ID, DESCONTO) VALUES
--(90.00, 1, 90.00, 2, 5, 0.00);

--INSERT INTO PEDIDO_PRODUTO (PRECO_UNITARIO, QUANTIDADE, SUBTOTAL, PEDIDO_ID, PRODUTO_ID, DESCONTO) VALUES
--(120.00, 1, 120.00, 3, 8, 0.00);